name: deploy-site

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo $GITHUB_REF
